export const DESIRED_ADVERTISEMENT_SPOT_COUNT = 2;
export const DESIRED_ADVERTISEMENT_COUNT = 3;
export const DEFAULT_SCORE_THRESHOLD = 1;
export const WEBPAGE_LOOK_BACK_DAYS = 90;
export const FETCH_TIMEOUT = 5_000;
export const CHAT_GPT_FETCH_TIMEOUT = 20_000;
