-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "brandDescription" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "brandName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "clickUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "fixedCpm" DECIMAL(10,2) NOT NULL DEFAULT 10.00,
ADD COLUMN     "impressionCap" INTEGER NOT NULL DEFAULT 1000000,
ADD COLUMN     "pacing" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requiredCssSelector" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "name" SET DEFAULT '';
